### ISSUE TITLE
ETA on the "Screen sharing + cams" feature?

### ISSUE THREAD

**Issue by DillFrescott** [lynoapp/mattermost-plugin-lyno#9]
This is a very interesting plugin. Cant wait for this feature to be added.

**Comment by sapkra** [comment]
We don't have an ETA for this right now but the feature is already there - only the UI has to be added, which can be done by the open source community.

We have very limited resources and we are changing a lot right now, so the mattermost plugin is currently a bit behind.

**Comment by DillFrescott** [comment]
@sapkra Understandable. Thank you for the response!
